export const MONACO_OPTIONS = {
	selectOnLineNumbers: true,
	fontSize: 14,
	fontFamily: 'jetbrains mono',
	lineNumbers: 'on',
	roundedSelection: true,
	scrollBeyondLastLine: false,
	lineHeight: 20,
	autoClosingBrackets: 'always',
	autoIndent: 'full',
	snippetSuggestions: 'inline',
	quickSuggestions: true,
	matchBrackets: 'always',
	padding: { top: 10, bottom: 10 },
	automaticLayout: true,
	autoClosingComments: 'always',
	colorDecorators: true,
	cursorStyle: 'underline',
	folding: true,
	foldingHighlight: true,
	fontLigatures: true,
	links: true,
	tabFocusMode: true,
	tabSize: 4,
	defaultColorDecorators: true,
	stickyScroll: {
		enabled: true,
		maxLineCount: 8,
		defaultModel: 'outlineModel',
		scrollWithEditor: true,
	},
};
